### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by ywarezk** [BenSchajnovitz/React-Course#1]
Arrange project folder structure based on feature modules:

/src/common
/src/common/App/App.js
/src/todo/TodoList/TodoList.js
/src/todo/services/

From each module decide what is public with a barrel file:
/src/todo/index.js // this will expose what is public from this module
The import in App.js will import from that index file and not directly from the TodoList folder

**Comment by BenSchajnovitz** [comment]
Solved, thanks
