### ISSUE TITLE
propTypes, defaultProps as static 

### ISSUE THREAD

**Issue by ywarezk** [BenSchajnovitz/React-Course#2]
https://github.com/BenSchajnovitz/React-Course/blob/6b8a0c47d0996b7f57dab54c8912465dfefb7755/Exercise%204/src/TodoList/TodoListClass.js#L75

When writing a class component, specify the defaultProps and propTypes as static memebers of the class

```
class TodoList extends Component {
    static propTypes = {... }
    static defaultProps = { ... }
}
```

**Comment by BenSchajnovitz** [comment]
Redefined, thanks
